In [1]:
import IsingLib
import numpy as np

num = 20
value = 31
mat = np.random.randint(-value, value, (num, num))
print(mat)

[[-30 -20  -1  28  25  -9 -15   7 -20  13 -24 -28 -19 -11  -8  -2   4 -30
   24  -3]
 [ 24   5  14 -10  16 -11  24  11   4 -19 -16  22  24 -15 -10   2  16  -6
   21 -17]
 [ -5  -7   7 -15  -5  20  -7  17   9   1 -26   1  -6  11  11 -31  20   9
    9 -28]
 [ -2   3 -26   6  30 -30 -24 -10  27   8  -8  17 -29   7 -16 -25   5   9
   21   4]
 [ -8  24  -6  19   1 -29  -1  29  30 -27  -7 -28 -12  11 -16 -13  27  17
   27  25]
 [ 30 -18  29   8  -7   8  23   4  17 -20  29  -4  29 -17  -8  28 -14   6
   11  24]
 [  8 -15  17   3   1  -4  10  10 -23  -7  -2  26  21 -29   1  -3  22 -15
    0  19]
 [-23  29 -29   0  26 -18  30   0 -26   9 -28  19  15  11 -11  -4  -7  29
   14 -29]
 [-11  -7 -14   5   7 -10 -27   4  -1  18  12  17  -5   4   4   5  -3 -26
  -20   7]
 [-22  23   6  11 -20  -2 -27  -6 -12 -11  23 -25 -20  -3   5 -25  15  -4
    6  10]
 [  0  22 -22  -8  10  17  20   4  18  23   0   2 -12   2 -16 -10  16  21
   15  -9]
 [  9  -7  -8   3  25 -22   2  11  -6   9  -9  24 -20  25  19   0

In [5]:
vartype = 'BINARY'
graph = IsingLib.Model(vartype)

In [6]:
graph.formulate(H=mat)
graph.compile()

In [7]:
print(graph.matrix)
s, eng = graph.solve(temperature_start=100000)
print(eng)

[[ -8.  23.  -7. -19.  10.   1.  -5.  14. -12. -15.   3.  24. -16. -12.
  -12. -31.  28.  12.  19. -16.]
 [  0.   5.  -4.  27.  23. -24. -14. -30.  20. -26.  -6.  -9. -27.  -9.
  -19.  -6.   0.  19.  19.  16.]
 [  0.   0. -22.  23.  -1. -27.  16.  10.  17. -14. -16. -12.   6.  -4.
    7. -11.  -7. -15.  -4. -10.]
 [  0.   0.   0. -20. -24.  26.  21.   2. -10. -24. -15.  -1. -27. -27.
   12. -23.  -1. -25.  24. -12.]
 [  0.   0.   0.   0. -30.  -7.  -1.  -4.  14. -10.  30. -31.   4.  21.
   -8.  10.   0. -31.   5.  -3.]
 [  0.   0.   0.   0.   0. -30. -28.   4.   3.  18.  -3.   3. -10.   7.
   -3.   5.  18.  -9. -27.  22.]
 [  0.   0.   0.   0.   0.   0. -17.  21.   7.   9. -10.   1. -10.  10.
  -24.  30. -26.  20. -10.  22.]
 [  0.   0.   0.   0.   0.   0.   0.  13. -25.  -6. -19.  23. -29.   0.
  -15.  27. -23.  29.  15. -12.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  12.   5.  -1.  11.  26.   6.
  -11.  27.   4. -31. -11.   7.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  14. -29

In [11]:
mat, const = graph.get_params('da')
da = IsingLib.DaFormat(mat, api_key='/Users/daisuke.oku/da_key_2.json', version=2)
job_id = da.da_solver()
da.get_job(job_id)

In [12]:
da.get_energy(job_id)
state_li = da.get_configuration(job_id)
for state in state_li:
    print(graph.energy(state))

-454.0
-454.0


In [15]:
graph.to_bqm()

BinaryQuadraticModel({0: -8.0, 1: 5.0, 2: -22.0, 3: -20.0, 4: -30.0, 5: -30.0, 6: -17.0, 7: 13.0, 8: 12.0, 9: 14.0, 10: 29.0, 11: 7.0, 12: -3.0, 13: 19.0, 14: 17.0, 15: -23.0, 16: -1.0, 17: -11.0, 18: 17.0, 19: -28.0}, {(0, 1): 23.0, (0, 2): -7.0, (0, 3): -19.0, (0, 4): 10.0, (0, 5): 1.0, (0, 6): -5.0, (0, 7): 14.0, (0, 8): -12.0, (0, 9): -15.0, (0, 10): 3.0, (0, 11): 24.0, (0, 12): -16.0, (0, 13): -12.0, (0, 14): -12.0, (0, 15): -31.0, (0, 16): 28.0, (0, 17): 12.0, (0, 18): 19.0, (0, 19): -16.0, (1, 2): -4.0, (1, 3): 27.0, (1, 4): 23.0, (1, 5): -24.0, (1, 6): -14.0, (1, 7): -30.0, (1, 8): 20.0, (1, 9): -26.0, (1, 10): -6.0, (1, 11): -9.0, (1, 12): -27.0, (1, 13): -9.0, (1, 14): -19.0, (1, 15): -6.0, (1, 17): 19.0, (1, 18): 19.0, (1, 19): 16.0, (2, 3): 23.0, (2, 4): -1.0, (2, 5): -27.0, (2, 6): 16.0, (2, 7): 10.0, (2, 8): 17.0, (2, 9): -14.0, (2, 10): -16.0, (2, 11): -12.0, (2, 12): 6.0, (2, 13): -4.0, (2, 14): 7.0, (2, 15): -11.0, (2, 16): -7.0, (2, 17): -15.0, (2, 18): -4.0, (2, 19):

In [2]:
a = IsingLib.Model.from_list(mat, 10, 'ising')
print(a)

ising model={'h': (array([[-30, -20,  -1,  28,  25,  -9, -15,   7, -20,  13, -24, -28, -19,
        -11,  -8,  -2,   4, -30,  24,  -3],
       [ 24,   5,  14, -10,  16, -11,  24,  11,   4, -19, -16,  22,  24,
        -15, -10,   2,  16,  -6,  21, -17],
       [ -5,  -7,   7, -15,  -5,  20,  -7,  17,   9,   1, -26,   1,  -6,
         11,  11, -31,  20,   9,   9, -28],
       [ -2,   3, -26,   6,  30, -30, -24, -10,  27,   8,  -8,  17, -29,
          7, -16, -25,   5,   9,  21,   4],
       [ -8,  24,  -6,  19,   1, -29,  -1,  29,  30, -27,  -7, -28, -12,
         11, -16, -13,  27,  17,  27,  25],
       [ 30, -18,  29,   8,  -7,   8,  23,   4,  17, -20,  29,  -4,  29,
        -17,  -8,  28, -14,   6,  11,  24],
       [  8, -15,  17,   3,   1,  -4,  10,  10, -23,  -7,  -2,  26,  21,
        -29,   1,  -3,  22, -15,   0,  19],
       [-23,  29, -29,   0,  26, -18,  30,   0, -26,   9, -28,  19,  15,
         11, -11,  -4,  -7,  29,  14, -29],
       [-11,  -7, -14,   5,   7, -10, -27,   

In [3]:
a.compile()

In [4]:
a.to_ising()

(array([[-30., -20.,  -1.,  28.,  25.,  -9., -15.,   7., -20.,  13., -24.,
         -28., -19., -11.,  -8.,  -2.,   4., -30.,  24.,  -3.],
        [  0.,   5.,  14., -10.,  16., -11.,  24.,  11.,   4., -19., -16.,
          22.,  24., -15., -10.,   2.,  16.,  -6.,  21., -17.],
        [  0.,   0.,   7., -15.,  -5.,  20.,  -7.,  17.,   9.,   1., -26.,
           1.,  -6.,  11.,  11., -31.,  20.,   9.,   9., -28.],
        [  0.,   0.,   0.,   6.,  30., -30., -24., -10.,  27.,   8.,  -8.,
          17., -29.,   7., -16., -25.,   5.,   9.,  21.,   4.],
        [  0.,   0.,   0.,   0.,   1., -29.,  -1.,  29.,  30., -27.,  -7.,
         -28., -12.,  11., -16., -13.,  27.,  17.,  27.,  25.],
        [  0.,   0.,   0.,   0.,   0.,   8.,  23.,   4.,  17., -20.,  29.,
          -4.,  29., -17.,  -8.,  28., -14.,   6.,  11.,  24.],
        [  0.,   0.,   0.,   0.,   0.,   0.,  10.,  10., -23.,  -7.,  -2.,
          26.,  21., -29.,   1.,  -3.,  22., -15.,   0.,  19.],
        [  0.,   0.,   0., 

In [5]:
a.to_qubo()

(array([[ 148.,  -80.,   -4.,  112.,  100.,  -36.,  -60.,   28.,  -80.,
           52.,  -96., -112.,  -76.,  -44.,  -32.,   -8.,   16., -120.,
           96.,  -12.],
        [   0.,  -55.,   56.,  -40.,   64.,  -44.,   96.,   44.,   16.,
          -76.,  -64.,   88.,   96.,  -60.,  -40.,    8.,   64.,  -24.,
           84.,  -68.],
        [   0.,    0.,    1.,  -60.,  -20.,   80.,  -28.,   68.,   36.,
            4., -104.,    4.,  -24.,   44.,   44., -124.,   80.,   36.,
           36., -112.],
        [   0.,    0.,    0.,   28.,  120., -120.,  -96.,  -40.,  108.,
           32.,  -32.,   68., -116.,   28.,  -64., -100.,   20.,   36.,
           84.,   16.],
        [   0.,    0.,    0.,    0., -197., -116.,   -4.,  116.,  120.,
         -108.,  -28., -112.,  -48.,   44.,  -64.,  -52.,  108.,   68.,
          108.,  100.],
        [   0.,    0.,    0.,    0.,    0.,  -90.,   92.,   16.,   68.,
          -80.,  116.,  -16.,  116.,  -68.,  -32.,  112.,  -56.,   24.,
           44., 

In [7]:
a.trans_matrix('qubo')

(array([[ 148.,  -80.,   -4.,  112.,  100.,  -36.,  -60.,   28.,  -80.,
           52.,  -96., -112.,  -76.,  -44.,  -32.,   -8.,   16., -120.,
           96.,  -12.],
        [   0.,  -55.,   56.,  -40.,   64.,  -44.,   96.,   44.,   16.,
          -76.,  -64.,   88.,   96.,  -60.,  -40.,    8.,   64.,  -24.,
           84.,  -68.],
        [   0.,    0.,    1.,  -60.,  -20.,   80.,  -28.,   68.,   36.,
            4., -104.,    4.,  -24.,   44.,   44., -124.,   80.,   36.,
           36., -112.],
        [   0.,    0.,    0.,   28.,  120., -120.,  -96.,  -40.,  108.,
           32.,  -32.,   68., -116.,   28.,  -64., -100.,   20.,   36.,
           84.,   16.],
        [   0.,    0.,    0.,    0., -197., -116.,   -4.,  116.,  120.,
         -108.,  -28., -112.,  -48.,   44.,  -64.,  -52.,  108.,   68.,
          108.,  100.],
        [   0.,    0.,    0.,    0.,    0.,  -90.,   92.,   16.,   68.,
          -80.,  116.,  -16.,  116.,  -68.,  -32.,  112.,  -56.,   24.,
           44., 

In [8]:
a.to_bqm()

BinaryQuadraticModel({0: 148.0, 1: -55.0, 2: 1.0, 3: 28.0, 4: -197.0, 5: -90.0, 6: -30.0, 7: -120.0, 8: -63.0, 9: 73.0, 10: 76.0, 11: 2.0, 12: 120.0, 13: -120.0, 14: 209.0, 15: 241.0, 16: -144.0, 17: 127.0, 18: -106.0, 19: 180.0}, {(0, 1): -80.0, (0, 2): -4.0, (0, 3): 112.0, (0, 4): 100.0, (0, 5): -36.0, (0, 6): -60.0, (0, 7): 28.0, (0, 8): -80.0, (0, 9): 52.0, (0, 10): -96.0, (0, 11): -112.0, (0, 12): -76.0, (0, 13): -44.0, (0, 14): -32.0, (0, 15): -8.0, (0, 16): 16.0, (0, 17): -120.0, (0, 18): 96.0, (0, 19): -12.0, (1, 2): 56.0, (1, 3): -40.0, (1, 4): 64.0, (1, 5): -44.0, (1, 6): 96.0, (1, 7): 44.0, (1, 8): 16.0, (1, 9): -76.0, (1, 10): -64.0, (1, 11): 88.0, (1, 12): 96.0, (1, 13): -60.0, (1, 14): -40.0, (1, 15): 8.0, (1, 16): 64.0, (1, 17): -24.0, (1, 18): 84.0, (1, 19): -68.0, (2, 3): -60.0, (2, 4): -20.0, (2, 5): 80.0, (2, 6): -28.0, (2, 7): 68.0, (2, 8): 36.0, (2, 9): 4.0, (2, 10): -104.0, (2, 11): 4.0, (2, 12): -24.0, (2, 13): 44.0, (2, 14): 44.0, (2, 15): -124.0, (2, 16): 80.0,