In [1]:
import IsingLib
import numpy as np
np.set_printoptions(threshold=1000)
np.set_printoptions(linewidth=200)

# Random Graph

num = 15
value = 31
mat = np.random.randint(-value, value, (num, num))
print(mat)

[[-13 -26 -23 -16 -18  26   1  26  27 -21 -28  -9   6 -25 -28]
 [ -5  19 -12  16  20  18  27  26 -11   4 -21   1  21 -28 -27]
 [ 20 -15 -21  30   3  -2  29   0 -28  -3   9   7   0 -29  25]
 [ 19  12  26   4  25 -11 -20 -17  28 -24 -30  14 -10 -10  15]
 [-11  28   8  10  14 -19   3  28   0  25 -31 -19   8 -10  17]
 [-11   5  17  -9 -22 -15  -8 -26  -6   5  25  15   8 -16   6]
 [ 15   8  10  24  12   2 -24   4   1  23  -2  17  28 -29  -8]
 [-15 -16 -22 -22   2 -11 -14  12   7 -15  -3 -23  20  -8 -25]
 [-25 -10 -15 -30  -7   7  -7 -23 -17 -10   8  28 -26   2  13]
 [-15   7  26 -17  14 -22 -17 -27 -28  29  -1  29  23 -27   2]
 [-29  -8   2   6 -12 -21 -15 -13   5   6  18  15 -28   0 -29]
 [-31  21   8  28 -22  25  -4 -16 -12  26  10 -19  18  19 -18]
 [-24  30   0  17 -12 -15  19 -23 -31 -24  24  -8  30 -15 -14]
 [  3 -17   5  27  30  16   7 -26  20  -6  22   5 -26 -30 -29]
 [-13   6 -23 -16  30  13  -9  12  14  15   0 -23  26 -24   7]]


In [2]:
vartype = 'BINARY'
# If you make a qubo model, you assign 'BINARY' or 'qubo' to variable vartype.
# if you make a Ising model, you assign 'SPIN' or 'ising' to variable vartype.

graph = IsingLib.Model(vartype)

In [3]:
graph.add_terms(H=mat)
graph.compile()

In [4]:
print(graph.matrix)
s, eng = graph.solve()
print(eng)

[[-13. -26. -23. -16. -18.  26.   1.  26.  27. -21. -28.  -9.   6. -25. -28.]
 [  0.  19. -12.  16.  20.  18.  27.  26. -11.   4. -21.   1.  21. -28. -27.]
 [  0.   0. -21.  30.   3.  -2.  29.   0. -28.  -3.   9.   7.   0. -29.  25.]
 [  0.   0.   0.   4.  25. -11. -20. -17.  28. -24. -30.  14. -10. -10.  15.]
 [  0.   0.   0.   0.  14. -19.   3.  28.   0.  25. -31. -19.   8. -10.  17.]
 [  0.   0.   0.   0.   0. -15.  -8. -26.  -6.   5.  25.  15.   8. -16.   6.]
 [  0.   0.   0.   0.   0.   0. -24.   4.   1.  23.  -2.  17.  28. -29.  -8.]
 [  0.   0.   0.   0.   0.   0.   0.  12.   7. -15.  -3. -23.  20.  -8. -25.]
 [  0.   0.   0.   0.   0.   0.   0.   0. -17. -10.   8.  28. -26.   2.  13.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  29.  -1.  29.  23. -27.   2.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  18.  15. -28.   0. -29.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. -19.  18.  19. -18.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  3

In [5]:
graph.solve('bf')

{(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): 0.0,
 (1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): -13.0,
 (0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): 19.0,
 (1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): -20.0,
 (0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): -21.0,
 (1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): -57.0,
 (0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): -14.0,
 (1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): -76.0,
 (0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): 4.0,
 (1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): -25.0,
 (0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): 39.0,
 (1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): -16.0,
 (0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): 13.0,
 (1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): -39.0,
 (0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): 36.0,
 (1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): -42.0,
 (0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): 14.0,
 (1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): -17.0,
 (0, 1, 0, 0, 1, 0,

In [58]:
mat, const = graph.get_params('da')
da = IsingLib.DaFormat(mat, api_key='/Users/daisuke.oku/da_key_2.json', version=2)
job_id = da.da_solver()
da.get_job(job_id)

In [59]:
da.get_energy(job_id)
state_li = da.get_configuration(job_id)
for state in state_li:
    print(graph.energy(state))

-364.0


In [60]:
# TSP
import pyqubo

city = 5
vartype = 'BINARY'
x = pyqubo.Array.create('x', (city, city), vartype)
tsp_model = IsingLib.Model(vartype)
dis_li = [[0, 10, 8, 8, 4], [10, 0, 6, 11, 7], [8, 6, 0, 14, 8], [9, 11, 14, 0, 6], [4, 7, 8, 6, 0]]
distance = np.zeros((city**2, city**2))
for i in range(city):
    point = (i + 1) % city
    distance[i*city: (i+1)*city, point*city: (point+1)*city] = dis_li
time_const = pyqubo.Sum(0, city, lambda i: (pyqubo.Sum(0, city, lambda j: x[i, j]) - 1) ** 2)
city_const = pyqubo.Sum(0, city, lambda j: (pyqubo.Sum(0, city, lambda i: x[i, j]) - 1) ** 2)
tsp_model.add_terms(H_0=distance, H_1=time_const, H_2=city_const)

In [62]:
np.set_printoptions(edgeitems=7)
A = 10
tsp_model.compile(H_1=A, H_2=A)
print(tsp_model.matrix)

[[-20.  20.  20.  20.  20.  20.  10.   8.   8.   4.  20.   0.   0.   0.   0.  20.   0.   0.   0.   0.  20.   0.   0.   0.   0.]
 [  0. -20.  20.  20.  20.  10.  20.   6.  11.   7.   0.  20.   0.   0.   0.   0.  20.   0.   0.   0.   0.  20.   0.   0.   0.]
 [  0.   0. -20.  20.  20.   8.   6.  20.  14.   8.   0.   0.  20.   0.   0.   0.   0.  20.   0.   0.   0.   0.  20.   0.   0.]
 [  0.   0.   0. -20.  20.   9.  11.  14.  20.   6.   0.   0.   0.  20.   0.   0.   0.   0.  20.   0.   0.   0.   0.  20.   0.]
 [  0.   0.   0.   0. -20.   4.   7.   8.   6.  20.   0.   0.   0.   0.  20.   0.   0.   0.   0.  20.   0.   0.   0.   0.  20.]
 [  0.   0.   0.   0.   0. -20.  20.  20.  20.  20.  20.  10.   8.   8.   4.  20.   0.   0.   0.   0.  20.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0. -20.  20.  20.  20.  10.  20.   6.  11.   7.   0.  20.   0.   0.   0.   0.  20.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. -20.  20.  20.   8.   6.  20.  14.   8.   0.   0.  20.   0.   0.   

In [63]:
state, eng = tsp_model.solve(temperature_start=100000, temperature_end=0.001)
print('')
print(state, )
print('')
ans = state.reshape(city, city)
print(ans)


[0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0]

[[0 1 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]]


In [64]:
mat, const = tsp_model.get_params('da')
da = IsingLib.DaFormat(mat, api_key='/Users/daisuke.oku/da_key_2.json', version=2)
job_id = da.da_solver()
da.get_job(job_id)

In [65]:
da.get_energy(job_id)
state_li = da.get_configuration(job_id)
for state in state_li:
    np_state = np.array(state).reshape(city, city)
    print(np_state, tsp_model.energy(state))

[[0 0 0 1 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]] -76.0
[[0 1 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]] -76.0
