In [1]:
import IsingLib
import numpy as np

num = 100
value = 31
mat = np.random.randint(-value, value, (num, num))

In [2]:
vartype = 'BINARY'
graph = IsingLib.Model(vartype)

In [3]:
graph.formulate(H=mat)
graph.compile()

In [4]:
print(graph.matrix)
s, eng = graph.solve(temperature_start=100000)
print(eng)

[[ 17. -19.  -7. ...  16.  -6.  -5.]
 [  0. -19. -27. ...   8.   4.  26.]
 [  0.   0.  24. ...  29.   5. -21.]
 ...
 [  0.   0.   0. ...  -5. -20. -17.]
 [  0.   0.   0. ...   0.  22.  -9.]
 [  0.   0.   0. ...   0.   0.  -5.]]
-6576.0


In [5]:
mat, const = graph.get_params('da')
da = IsingLib.DaFormat(mat, api_key='/Users/daisuke.oku/da_key_2.json', version=2)
job_id = da.da_solver()

In [6]:
da.get_job(job_id)
da.get_energy(job_id)
state_li = da.get_configuration(job_id)
for state in state_li:
    print(graph.calc_eng(state))

-6576.0


In [7]:
da.check_job()

[]