In [17]:
import IsingLib
import numpy as np
np.set_printoptions(threshold=1000)
np.set_printoptions(linewidth=200)

num = 15
value = 31
mat = np.random.randint(-value, value, (num, num))
print(mat)

[[  2  -9  18  18  25  -2   0  26   8   6  11   2 -28 -27 -13]
 [-30 -16  -9  20 -26  20 -22   4  -2  21 -26  -5  -9  18  25]
 [ -3  25   5  12   4  -5 -17  29  11 -28 -30  28  27  28   5]
 [-13 -12   2 -28 -29  -1 -26  30 -29 -28 -14  -4  17 -18 -14]
 [ 29   4  25 -23  19  -4  23 -10 -19  -8 -10  12 -12  10  16]
 [ 21  -3   5 -27 -21  17  23  26  19   1  -9 -28  28 -22 -17]
 [ 27 -23  16  26  -7 -26  12  22  24  -5  28 -15  13 -26  10]
 [ 25  27   8 -26  18 -30  24   4 -25 -22  11  20  -6 -28  14]
 [ 22   0 -18   3  10  30  15 -21 -23  -5   6  -9 -13  24  17]
 [ 21  18 -26  -6 -26   2 -11 -26   0  26  28  13   7  30 -30]
 [ -5 -17  21   1 -18 -14  23  -3  -3   5  15 -22   3   2 -11]
 [ -8 -22  17 -31 -18  24  17  10 -21  30   4 -29  -1  21 -20]
 [-18  -9  14  28  -4   5  19  10 -25  22  -5 -15  -8  21 -22]
 [ 22 -12  17  21 -28 -22 -17 -10 -10  17  27  -7 -13 -10 -24]
 [-18  17   3  17 -20  -1 -10  21  23 -12 -21  30   7   2  23]]


In [18]:
vartype = 'BINARY'
# If you make a qubo model, you assign 'BINARY' or 'qubo' to variable vartype.
# if you make a Ising model, you assign 'SPIN' or 'ising' to variable vartype.

graph = IsingLib.Model(vartype)

In [19]:
graph.add_terms(H=mat)
graph.compile()

In [21]:
print(graph.matrix)
s, eng = graph.solve(temperature_start=100000)
print(eng)

[[  2.  -9.  18.  18.  25.  -2.   0.  26.   8.   6.  11.   2. -28. -27. -13.]
 [  0. -16.  -9.  20. -26.  20. -22.   4.  -2.  21. -26.  -5.  -9.  18.  25.]
 [  0.   0.   5.  12.   4.  -5. -17.  29.  11. -28. -30.  28.  27.  28.   5.]
 [  0.   0.   0. -28. -29.  -1. -26.  30. -29. -28. -14.  -4.  17. -18. -14.]
 [  0.   0.   0.   0.  19.  -4.  23. -10. -19.  -8. -10.  12. -12.  10.  16.]
 [  0.   0.   0.   0.   0.  17.  23.  26.  19.   1.  -9. -28.  28. -22. -17.]
 [  0.   0.   0.   0.   0.   0.  12.  22.  24.  -5.  28. -15.  13. -26.  10.]
 [  0.   0.   0.   0.   0.   0.   0.   4. -25. -22.  11.  20.  -6. -28.  14.]
 [  0.   0.   0.   0.   0.   0.   0.   0. -23.  -5.   6.  -9. -13.  24.  17.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  26.  28.  13.   7.  30. -30.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  15. -22.   3.   2. -11.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. -29.  -1.  21. -20.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  -

In [16]:
mat, const = graph.get_params('da')
#　今日は動かない
da = IsingLib.DaFormat(mat, api_key='/Users/daisuke.oku/da_key_2.json', version=2)
job_id = da.da_solver()
da.get_job(job_id)

ConnectionError: HTTPSConnectionPool(host='api.jp-east-1.digitalannealer.global.fujitsu.com', port=443): Max retries exceeded with url: /v2/async/qubo/solve (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x12266d940>: Failed to establish a new connection: [Errno 61] Connection refused'))

In [12]:
da.get_energy(job_id)
state_li = da.get_configuration(job_id)
for state in state_li:
    print(graph.energy(state))

-454.0
-454.0


In [22]:
graph.to_bqm()

BinaryQuadraticModel({0: 2.0, 1: -16.0, 2: 5.0, 3: -28.0, 4: 19.0, 5: 17.0, 7: 4.0, 8: -23.0, 9: 26.0, 10: 15.0, 11: -29.0, 12: -8.0, 13: -10.0, 14: 23.0, 6: 12.0}, {(0, 1): -9.0, (0, 2): 18.0, (0, 3): 18.0, (0, 4): 25.0, (0, 5): -2.0, (0, 7): 26.0, (0, 8): 8.0, (0, 9): 6.0, (0, 10): 11.0, (0, 11): 2.0, (0, 12): -28.0, (0, 13): -27.0, (0, 14): -13.0, (1, 2): -9.0, (1, 3): 20.0, (1, 4): -26.0, (1, 5): 20.0, (1, 6): -22.0, (1, 7): 4.0, (1, 8): -2.0, (1, 9): 21.0, (1, 10): -26.0, (1, 11): -5.0, (1, 12): -9.0, (1, 13): 18.0, (1, 14): 25.0, (2, 3): 12.0, (2, 4): 4.0, (2, 5): -5.0, (2, 6): -17.0, (2, 7): 29.0, (2, 8): 11.0, (2, 9): -28.0, (2, 10): -30.0, (2, 11): 28.0, (2, 12): 27.0, (2, 13): 28.0, (2, 14): 5.0, (3, 4): -29.0, (3, 5): -1.0, (3, 6): -26.0, (3, 7): 30.0, (3, 8): -29.0, (3, 9): -28.0, (3, 10): -14.0, (3, 11): -4.0, (3, 12): 17.0, (3, 13): -18.0, (3, 14): -14.0, (4, 5): -4.0, (4, 6): 23.0, (4, 7): -10.0, (4, 8): -19.0, (4, 9): -8.0, (4, 10): -10.0, (4, 11): 12.0, (4, 12): -12.0,

In [23]:
a = IsingLib.Model.from_list(mat, 10, 'ising')
print(a)

ising model={'h': (array([[  2,  -9,  18,  18,  25,  -2,   0,  26,   8,   6,  11,   2, -28, -27, -13],
       [-30, -16,  -9,  20, -26,  20, -22,   4,  -2,  21, -26,  -5,  -9,  18,  25],
       [ -3,  25,   5,  12,   4,  -5, -17,  29,  11, -28, -30,  28,  27,  28,   5],
       [-13, -12,   2, -28, -29,  -1, -26,  30, -29, -28, -14,  -4,  17, -18, -14],
       [ 29,   4,  25, -23,  19,  -4,  23, -10, -19,  -8, -10,  12, -12,  10,  16],
       [ 21,  -3,   5, -27, -21,  17,  23,  26,  19,   1,  -9, -28,  28, -22, -17],
       [ 27, -23,  16,  26,  -7, -26,  12,  22,  24,  -5,  28, -15,  13, -26,  10],
       [ 25,  27,   8, -26,  18, -30,  24,   4, -25, -22,  11,  20,  -6, -28,  14],
       [ 22,   0, -18,   3,  10,  30,  15, -21, -23,  -5,   6,  -9, -13,  24,  17],
       [ 21,  18, -26,  -6, -26,   2, -11, -26,   0,  26,  28,  13,   7,  30, -30],
       [ -5, -17,  21,   1, -18, -14,  23,  -3,  -3,   5,  15, -22,   3,   2, -11],
       [ -8, -22,  17, -31, -18,  24,  17,  10, -21,  30,

In [24]:
a.compile()

In [25]:
a.to_ising()

(array([[  2.,  -9.,  18.,  18.,  25.,  -2.,   0.,  26.,   8.,   6.,  11.,   2., -28., -27., -13.],
        [  0., -16.,  -9.,  20., -26.,  20., -22.,   4.,  -2.,  21., -26.,  -5.,  -9.,  18.,  25.],
        [  0.,   0.,   5.,  12.,   4.,  -5., -17.,  29.,  11., -28., -30.,  28.,  27.,  28.,   5.],
        [  0.,   0.,   0., -28., -29.,  -1., -26.,  30., -29., -28., -14.,  -4.,  17., -18., -14.],
        [  0.,   0.,   0.,   0.,  19.,  -4.,  23., -10., -19.,  -8., -10.,  12., -12.,  10.,  16.],
        [  0.,   0.,   0.,   0.,   0.,  17.,  23.,  26.,  19.,   1.,  -9., -28.,  28., -22., -17.],
        [  0.,   0.,   0.,   0.,   0.,   0.,  12.,  22.,  24.,  -5.,  28., -15.,  13., -26.,  10.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   4., -25., -22.,  11.,  20.,  -6., -28.,  14.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., -23.,  -5.,   6.,  -9., -13.,  24.,  17.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  26.,  28.,  13.,   7.,  30., -30.],


In [26]:
a.to_qubo()

(array([[ -68.,  -36.,   72.,   72.,  100.,   -8.,    0.,  104.,   32.,   24.,   44.,    8., -112., -108.,  -52.],
        [   0.,  -16.,  -36.,   80., -104.,   80.,  -88.,   16.,   -8.,   84., -104.,  -20.,  -36.,   72.,  100.],
        [   0.,    0., -141.,   48.,   16.,  -20.,  -68.,  116.,   44., -112., -120.,  112.,  108.,  112.,   20.],
        [   0.,    0.,    0.,  104., -116.,   -4., -104.,  120., -116., -112.,  -56.,  -16.,   68.,  -72.,  -56.],
        [   0.,    0.,    0.,    0.,   75.,  -16.,   92.,  -40.,  -76.,  -32.,  -40.,   48.,  -48.,   40.,   64.],
        [   0.,    0.,    0.,    0.,    0.,  -41.,   92.,  104.,   76.,    4.,  -36., -112.,  112.,  -88.,  -68.],
        [   0.,    0.,    0.,    0.,    0.,    0.,  -52.,   88.,   96.,  -20.,  112.,  -60.,   52., -104.,   40.],
        [   0.,    0.,    0.,    0.,    0.,    0.,    0., -178., -100.,  -88.,   44.,   80.,  -24., -112.,   56.],
        [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,  -37.,  -20.,  

In [7]:
a.trans_matrix('qubo')

(array([[ 148.,  -80.,   -4.,  112.,  100.,  -36.,  -60.,   28.,  -80.,
           52.,  -96., -112.,  -76.,  -44.,  -32.,   -8.,   16., -120.,
           96.,  -12.],
        [   0.,  -55.,   56.,  -40.,   64.,  -44.,   96.,   44.,   16.,
          -76.,  -64.,   88.,   96.,  -60.,  -40.,    8.,   64.,  -24.,
           84.,  -68.],
        [   0.,    0.,    1.,  -60.,  -20.,   80.,  -28.,   68.,   36.,
            4., -104.,    4.,  -24.,   44.,   44., -124.,   80.,   36.,
           36., -112.],
        [   0.,    0.,    0.,   28.,  120., -120.,  -96.,  -40.,  108.,
           32.,  -32.,   68., -116.,   28.,  -64., -100.,   20.,   36.,
           84.,   16.],
        [   0.,    0.,    0.,    0., -197., -116.,   -4.,  116.,  120.,
         -108.,  -28., -112.,  -48.,   44.,  -64.,  -52.,  108.,   68.,
          108.,  100.],
        [   0.,    0.,    0.,    0.,    0.,  -90.,   92.,   16.,   68.,
          -80.,  116.,  -16.,  116.,  -68.,  -32.,  112.,  -56.,   24.,
           44., 

In [8]:
a.to_bqm()

BinaryQuadraticModel({0: 148.0, 1: -55.0, 2: 1.0, 3: 28.0, 4: -197.0, 5: -90.0, 6: -30.0, 7: -120.0, 8: -63.0, 9: 73.0, 10: 76.0, 11: 2.0, 12: 120.0, 13: -120.0, 14: 209.0, 15: 241.0, 16: -144.0, 17: 127.0, 18: -106.0, 19: 180.0}, {(0, 1): -80.0, (0, 2): -4.0, (0, 3): 112.0, (0, 4): 100.0, (0, 5): -36.0, (0, 6): -60.0, (0, 7): 28.0, (0, 8): -80.0, (0, 9): 52.0, (0, 10): -96.0, (0, 11): -112.0, (0, 12): -76.0, (0, 13): -44.0, (0, 14): -32.0, (0, 15): -8.0, (0, 16): 16.0, (0, 17): -120.0, (0, 18): 96.0, (0, 19): -12.0, (1, 2): 56.0, (1, 3): -40.0, (1, 4): 64.0, (1, 5): -44.0, (1, 6): 96.0, (1, 7): 44.0, (1, 8): 16.0, (1, 9): -76.0, (1, 10): -64.0, (1, 11): 88.0, (1, 12): 96.0, (1, 13): -60.0, (1, 14): -40.0, (1, 15): 8.0, (1, 16): 64.0, (1, 17): -24.0, (1, 18): 84.0, (1, 19): -68.0, (2, 3): -60.0, (2, 4): -20.0, (2, 5): 80.0, (2, 6): -28.0, (2, 7): 68.0, (2, 8): 36.0, (2, 9): 4.0, (2, 10): -104.0, (2, 11): 4.0, (2, 12): -24.0, (2, 13): 44.0, (2, 14): 44.0, (2, 15): -124.0, (2, 16): 80.0,