In [1]:
from dimod import *

linear = {1: 1, 2: 2, 3: 3, 4: 4}
quadratic = {(1, 2): 12, (1, 3): 13, (1, 4): 14, (2, 3): 23, (2, 4): 24, (3, 4): 34}
offset = 0.0
vartype = dimod.SPIN
bqm_k4 = dimod.BinaryQuadraticModel(linear, quadratic, offset, vartype)
print(bqm_k4)

BinaryQuadraticModel({1: 1, 2: 2, 3: 3, 4: 4}, {(1, 2): 12, (1, 3): 13, (1, 4): 14, (2, 3): 23, (2, 4): 24, (3, 4): 34}, 0.0, Vartype.SPIN)


In [5]:
sampleset = ExactSolver().sample(bqm_k4)
print(sampleset)

    1  2  3  4 energy num_oc.
6  +1 -1 +1 -1  -48.0       1
4  -1 +1 +1 -1  -46.0       1
14 +1 -1 -1 +1  -46.0       1
12 -1 +1 -1 +1  -44.0       1
2  +1 +1 -1 -1  -32.0       1
15 -1 -1 -1 +1  -26.0       1
7  -1 -1 +1 -1  -24.0       1
8  -1 -1 +1 +1  -24.0       1
5  +1 +1 +1 -1  -22.0       1
13 +1 +1 -1 +1  -16.0       1
3  -1 +1 -1 -1   -4.0       1
9  +1 -1 +1 +1    8.0       1
1  +1 -1 -1 -1   34.0       1
11 -1 +1 +1 +1   50.0       1
0  -1 -1 -1 -1  110.0       1
10 +1 +1 +1 +1  130.0       1
['SPIN', 16 rows, 16 samples, 4 variables]


In [33]:
mat = bqm_k4.to_numpy_matrix(bqm_k4.linear)
print(mat)

[[ -76.   48.   52.   56.]
 [   0. -114.   92.   96.]
 [   0.    0. -134.  136.]
 [   0.    0.    0. -136.]]


In [34]:
mat_qubo = BinaryQuadraticModel.from_numpy_matrix(mat)
print(mat_qubo)

BinaryQuadraticModel({0: -76.0, 1: -114.0, 2: -134.0, 3: -136.0}, {(0, 1): 48.0, (0, 2): 52.0, (0, 3): 56.0, (1, 2): 92.0, (1, 3): 96.0, (2, 3): 136.0}, 0.0, Vartype.BINARY)


In [36]:
mat_ising = mat_qubo.to_ising()
print(mat_ising)

({0: 1.0, 1: 2.0, 2: 3.0, 3: 4.0}, {(0, 1): 12.0, (0, 2): 13.0, (0, 3): 14.0, (1, 2): 23.0, (1, 3): 24.0, (2, 3): 34.0}, -110.0)


In [40]:
li = {0: -76.0, 1: -114.0, 2: -134.0, 3: -136.0}
qu = {(0, 1): 48.0, (0, 2): 52.0, (0, 3): 56.0, (1, 2): 92.0, (1, 3): 96.0, (2, 3): 136.0}
bqm = BinaryQuadraticModel(li, qu, 0, 'SPIN')
print(bqm)

BinaryQuadraticModel({0: -76.0, 1: -114.0, 2: -134.0, 3: -136.0}, {(0, 1): 48.0, (0, 2): 52.0, (0, 3): 56.0, (1, 2): 92.0, (1, 3): 96.0, (2, 3): 136.0}, 0, Vartype.SPIN)


In [46]:
a = BinaryQuadraticModel.from_numpy_matrix(mat, 10)
print(a)
a.change_vartype('BINARY')

TypeError: 'int' object is not subscriptable

In [ ]:
p