In [2]:
from dimod import *

linear = {1: 1, 2: 2, 3: 3, 4: 4}
quadratic = {(1, 2): 12, (1, 3): 13, (1, 4): 14, (2, 3): 23, (2, 4): 24, (3, 4): 34}
offset = 0.0
vartype = dimod.SPIN
bqm_k4 = dimod.BinaryQuadraticModel(linear, quadratic, offset, vartype)
print(bqm_k4)

BinaryQuadraticModel({1: 1, 2: 2, 3: 3, 4: 4}, {(1, 2): 12, (1, 3): 13, (1, 4): 14, (2, 3): 23, (2, 4): 24, (3, 4): 34}, 0.0, Vartype.SPIN)


In [3]:
sampleset = ExactSolver().sample(bqm_k4)
print(sampleset)

    1  2  3  4 energy num_oc.
6  +1 -1 +1 -1  -48.0       1
4  -1 +1 +1 -1  -46.0       1
14 +1 -1 -1 +1  -46.0       1
12 -1 +1 -1 +1  -44.0       1
2  +1 +1 -1 -1  -32.0       1
15 -1 -1 -1 +1  -26.0       1
7  -1 -1 +1 -1  -24.0       1
8  -1 -1 +1 +1  -24.0       1
5  +1 +1 +1 -1  -22.0       1
13 +1 +1 -1 +1  -16.0       1
3  -1 +1 -1 -1   -4.0       1
9  +1 -1 +1 +1    8.0       1
1  +1 -1 -1 -1   34.0       1
11 -1 +1 +1 +1   50.0       1
0  -1 -1 -1 -1  110.0       1
10 +1 +1 +1 +1  130.0       1
['SPIN', 16 rows, 16 samples, 4 variables]


In [4]:
mat = bqm_k4.to_numpy_matrix(bqm_k4.linear)
print(mat)

[[ -76.   48.   52.   56.]
 [   0. -114.   92.   96.]
 [   0.    0. -134.  136.]
 [   0.    0.    0. -136.]]


In [6]:
import neal

r = neal.SimulatedAnnealingSampler().sample(bqm_k4)
print(r)

   1  2  3  4 energy num_oc.
2 +1 -1 +1 -1  -48.0       1
7 +1 -1 +1 -1  -48.0       1
8 +1 -1 +1 -1  -48.0       1
1 +1 -1 -1 +1  -46.0       1
3 +1 -1 -1 +1  -46.0       1
4 +1 -1 -1 +1  -46.0       1
5 -1 +1 +1 -1  -46.0       1
6 -1 +1 +1 -1  -46.0       1
9 +1 -1 -1 +1  -46.0       1
0 -1 +1 -1 +1  -44.0       1
['SPIN', 10 rows, 10 samples, 4 variables]


In [10]:
from dwave.system.samplers import DWaveSampler
from dwave.system.composites import EmbeddingComposite

sampler = EmbeddingComposite(DWaveSampler())
response = sampler.sample(bqm_k4)
print(response)

TypeError: 'EmbeddingComposite' object is not iterable