In [42]:
from dimod import *

linear = {1: -1, 2: -2, 3: -3, 4: -4}
quadratic = {(1, 2): 12, (1, 3): 13, (1, 4): 14, (2, 3): 23, (2, 4): 24, (3, 4): 20}
offset = 0.0
vartype = dimod.BINARY
bqm_k4 = dimod.BinaryQuadraticModel(linear, quadratic, offset, vartype)
print(bqm_k4)

BinaryQuadraticModel({1: -1, 2: -2, 3: -3, 4: -4}, {(1, 2): 12, (1, 3): 13, (1, 4): 14, (2, 3): 23, (2, 4): 24, (3, 4): 20}, 0.0, Vartype.BINARY)


In [43]:
sampleset = ExactSolver().sample(bqm_k4)
print(sampleset)

    1  2  3  4 energy num_oc.
15  0  0  0  1   -4.0       1
7   0  0  1  0   -3.0       1
3   0  1  0  0   -2.0       1
1   1  0  0  0   -1.0       1
0   0  0  0  0    0.0       1
2   1  1  0  0    9.0       1
6   1  0  1  0    9.0       1
14  1  0  0  1    9.0       1
8   0  0  1  1   13.0       1
4   0  1  1  0   18.0       1
12  0  1  0  1   18.0       1
9   1  0  1  1   39.0       1
5   1  1  1  0   42.0       1
13  1  1  0  1   43.0       1
11  0  1  1  1   58.0       1
10  1  1  1  1   96.0       1
['BINARY', 16 rows, 16 samples, 4 variables]


In [48]:
mat = bqm_k4.to_numpy_matrix(bqm_k4.linear)
print(mat)

[[-1. 12. 13. 14.]
 [ 0. -2. 23. 24.]
 [ 0.  0. -3. 20.]
 [ 0.  0.  0. -4.]]


In [49]:
import neal

r = neal.SimulatedAnnealingSampler().sample(bqm_k4)
print(r)

   1  2  3  4 energy num_oc.
0  0  0  0  1   -4.0       1
['BINARY', 1 rows, 1 samples, 4 variables]


In [50]:
from dwave.system.samplers import DWaveSampler
from dwave.system.composites import EmbeddingComposite

sampler = EmbeddingComposite(DWaveSampler())
response = sampler.sample(bqm_k4, num_reads=100)

In [53]:
response.info

{'timing': {'qpu_sampling_time': 31496,
  'qpu_anneal_time_per_sample': 20,
  'qpu_readout_time_per_sample': 274,
  'qpu_access_time': 41190,
  'qpu_access_overhead_time': 2513,
  'qpu_programming_time': 9694,
  'qpu_delay_time_per_sample': 21,
  'total_post_processing_time': 7500,
  'post_processing_overhead_time': 7500,
  'total_real_time': 41190,
  'run_time_chip': 31496,
  'anneal_time_per_run': 20,
  'readout_time_per_run': 274}}