In [1]:
import re
import numpy as np

In [4]:
str_dict = {'x[0][1]': 0, 'x[0][10]': 1, 'x[0][2]': 0, 'x[0][3]': 0, 'x[0][4]': 0, 
            'y[1][0]': 0, 'y[1][1]': 0, 'y[1][2]': 1, 'y[1][3]': 0, 'y[1][4]': 0,
            'a[2][0]': 1, 'a[2][1]': 0, 'a[2][2]': 0, 'a[2][3]': 0, 'a[2][4]': 0,
            'b[3][0]': 0, 'b[3][1]': 0, 'b[3][2]': 0, 'b[3][3]': 0, 'b[3][4]': 1,
            'c': 0, 'd': 0, 'e': 0, 'f': 1, 'g': 0}
str_list = list(str_dict)
print(str_list)

['x[0][1]', 'x[0][10]', 'x[0][2]', 'x[0][3]', 'x[0][4]', 'y[1][0]', 'y[1][1]', 'y[1][2]', 'y[1][3]', 'y[1][4]', 'a[2][0]', 'a[2][1]', 'a[2][2]', 'a[2][3]', 'a[2][4]', 'b[3][0]', 'b[3][1]', 'b[3][2]', 'b[3][3]', 'b[3][4]', 'c', 'd', 'e', 'f', 'g']


In [7]:
structure = {}
for label in str_list:
    result_tmp = re.findall(r'\w+', label)
    result = [int(char) if char.isdigit() else char for char in result_tmp]
    structure[label] = result
label_sorted_list = sorted(structure.items(), key=lambda x: x[1])
label_sorted = [item[0] for item in label_sorted_list]
print(label_sorted)

['a[2][0]', 'a[2][1]', 'a[2][2]', 'a[2][3]', 'a[2][4]', 'b[3][0]', 'b[3][1]', 'b[3][2]', 'b[3][3]', 'b[3][4]', 'c', 'd', 'e', 'f', 'g', 'x[0][1]', 'x[0][2]', 'x[0][3]', 'x[0][4]', 'x[0][10]', 'y[1][0]', 'y[1][1]', 'y[1][2]', 'y[1][3]', 'y[1][4]']


In [82]:
result = re.findall('\w', aim)
print(result)

['c', '4', '4']


In [83]:
def get_symbol(symbol):
    re_symbol = re.compile(symbol)
    new_states = {}
    for key, value in str_dict.items():
        if re_symbol.match(key):
            new_states[key] = value
    return new_states

In [84]:
get_symbol('b')

{'b[3][0]': 0, 'b[3][1]': 0, 'b[3][2]': 0, 'b[3][3]': 0, 'b[3][4]': 1}

In [8]:
def get_symmetric(matrix):
    return np.triu(matrix, k=1) + np.triu(matrix).T

In [13]:
mat = np.random.randint(-5, 6, (4, 4))
print(mat)

[[ 4  1  4  5]
 [ 1 -5 -4  3]
 [ 0  3  4 -2]
 [ 5 -5  5 -1]]


In [14]:
get_symmetric(mat)

array([[ 4,  1,  4,  5],
       [ 1, -5, -4,  3],
       [ 4, -4,  4, -2],
       [ 5,  3, -2, -1]])

In [17]:
a = {i: i for i in range(10)}
b = {i: i for i in range(5)}
len(a)<len(b)

False

In [20]:
a = [{}]
if a is enpty:
    print(a)

NameError: name 'enpty' is not defined

In [21]:
if not None:
    print(1)

1
