In [1]:
from IsingLib import Model, DaFormat
import numpy as np

In [2]:
mat = np.random.randint(-10, 11, (5, 5))
model = Model('i', mat, 0)
print(model)

ising model=[[ -7.   1.  -6.   0.  -3.]
 [  0.   6.   5. -10.   2.]
 [  0.   0.   0.   8. -10.]
 [  0.   0.   0.   5.   8.]
 [  0.   0.   0.   0.  -5.]]


In [3]:
da_model = model.to_da()
print(da_model)

{'matrix': array([[  2.,   4., -24.,   0., -12.],
       [  0.,  16.,  20., -40.,   8.],
       [  0.,   0.,   6.,  32., -40.],
       [  0.,   0.,   0.,  -2.,  32.],
       [  0.,   0.,   0.,   0.,  -4.]]), 'const': -4.0, 'label2index': {'[0]': 0, '[1]': 1, '[2]': 2, '[3]': 3, '[4]': 4}}


In [2]:
da = DaFormat(**da_model, api_key='../../da_key_2.json', version=2)

NameError: name 'DaFormat' is not defined

In [1]:
da.check_job()

NameError: name 'da' is not defined

In [18]:
da.jobs

{'PV83946-191861951594325': {'qubo_solution': {'result_status': True,
   'solutions': [{'configuration': {'0': True,
      '1': False,
      '2': True,
      '3': False,
      '4': True},
     'energy': -72,
     'frequency': 100}],
   'timing': {'cpu_time': '1118',
    'detailed': {'anneal_time': '217'},
    'queue_time': '2081',
    'solve_time': '1335',
    'total_elapsed_time': '3416'}},
  'solver_input_parameters': {'expert_mode': 'false',
   'job_id': 'PV83946-191861951594325',
   'number_iterations': '1000000',
   'number_runs': '100',
   'offset_increase_rate': '0',
   'solution_mode': 'COMPLETE',
   'solver_name': 'FujitsuDA2',
   'temperature_decay (COMPUTED)': '7.44813e-06',
   'temperature_interval (COMPUTED)': '5',
   'temperature_mode (COMPUTED)': 'INVERSE',
   'temperature_start (COMPUTED)': '121.372',
   'timeout': '0'},
  'status': 'Deleted'}}

In [7]:
job_id = da.da_solver()

'PV83946-191861951594325'

In [8]:
da.get_job('PV83946-191861951594325')

In [10]:
da.get_configuration('PV83946-191861951594325')

[{'[0]': 1, '[1]': 0, '[2]': 1, '[3]': 0, '[4]': 1}]